#########################################################################################
##  UPDATE PROJECT DEPENDENCIES
#########################################################################################
name: Update Project Dependencies

#########################################################################################
##  WORKFLOW TRIGGER
#########################################################################################
on:
  schedule:
    - cron: '45 4 */14 * *'
  workflow_dispatch:

#########################################################################################
##  WORKFLOW CONCURRENCY
#########################################################################################
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#########################################################################################
##  WORKFLOW JOBS
#########################################################################################
jobs:
  UpdateNpmDependencies:
    name: Update NPM Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install & Update Dependencies
        run: npm run upd-pkg-ver

      - name: Commit & Push Changes
        run: |
          git config --global user.email "${{ vars.COMMIT_USER_EMAIL }}"
          git config --global user.name "${{ vars.COMMIT_USER_NAME }}"
          git add --update
          git commit -m "updated project npm dependencies" || exit 0
          git push --force
